definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  'admin_toolbar_tools__extra_links:user__logout':
    enabled: true
    menu_name: admin
    parent: admin_toolbar_tools.help
    expanded: false
    weight: 10
  standard__front_page:
    weight: -50
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
