# Schema for the configuration files of the tr_rulez module.

tr_rulez.settings:
  type: config_object
  mapping:
    ui_choice:
      type: integer
      label: 'Choose UI style to use for creating, editing, and listing Reaction Rules and Rules Configurations'

rules_expression.rules_xor:
  type: rules_expression
  label: 'Rules Xor'
  mapping:
    negate:
      type: boolean
      label: 'Negate'
    conditions:
      type: sequence
      label: 'Conditions'
      sequence:
        - type: rules_expression.[id]
